run:
  timeout: 10m
  allow-parallel-runners: true

issues:
  # don't skip warning about doc comments
  # don't exclude the default set of lint
  exclude-use-default: false
  exclude-dirs:
    - test
  exclude-files:
    - ".*_test\\.go"

linters:
  disable-all: true
  enable:
    - dupl
    - errcheck
    - exportloopref
    - ginkgolinter
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
