apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: validator-images
spec:
  images:
    - name: quay.io/validator-labs/validator:v0.1.17 # x-release-please-version
    - name: quay.io/validator-labs/validator-plugin-aws:v${AWS_VERSION}
    - name: quay.io/validator-labs/validator-plugin-azure:v${AZURE_VERSION}
    - name: quay.io/validator-labs/validator-plugin-kubescape:v${KUBESCAPE_VERSION}
    - name: quay.io/validator-labs/validator-plugin-maas:v${MAAS_VERSION}
    - name: quay.io/validator-labs/validator-plugin-network:v${NETWORK_VERSION}
    - name: quay.io/validator-labs/validator-plugin-oci:v${OCI_VERSION}
    - name: quay.io/validator-labs/validator-plugin-vsphere:v${VSPHERE_VERSION}
    - name: quay.io/validator-labs/validator-certs-init:1.0.0
    - name: gcr.io/spectro-images-public/release/spectro-cleanup:1.2.0
    - name: kindest/node:v1.30.2
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Charts
metadata:
  name: validator-charts
spec:
  charts:
    - name: validator
      repoURL: https://validator-labs.github.io/validator
      version: 0.1.17 # x-release-please-version
    - name: validator-plugin-aws
      repoURL: https://validator-labs.github.io/validator-plugin-aws
      version: ${AWS_VERSION}
    - name: validator-plugin-azure
      repoURL: https://validator-labs.github.io/validator-plugin-azure
      version: ${AZURE_VERSION}
    - name: validator-plugin-kubescape
      repoURL: https://validator-labs.github.io/validator-plugin-kubescape
      version: ${KUBESCAPE_VERSION}
    - name: validator-plugin-maas
      repoURL: https://validator-labs.github.io/validator-plugin-maas
      version: ${MAAS_VERSION}
    - name: validator-plugin-network
      repoURL: https://validator-labs.github.io/validator-plugin-network
      version: ${NETWORK_VERSION}
    - name: validator-plugin-oci
      repoURL: https://validator-labs.github.io/validator-plugin-oci
      version: ${OCI_VERSION}
    - name: validator-plugin-vsphere
      repoURL: https://validator-labs.github.io/validator-plugin-vsphere
      version: ${VSPHERE_VERSION}
---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Files
metadata:
  name: validator-files
spec:
  files:
    - name: validatorctl
      path: https://github.com/validator-labs/validatorctl/releases/download/v${VALIDATORCTL_VERSION}/validator-linux-ARCH