name: GoLicenses

on:
  pull_request:
  workflow_dispatch:

jobs:
  call-golicenses:
    uses: validator-labs/workflows/.github/workflows/golicenses.yaml@533081ac49a832a478062407e23e559db6545f1d # main
    secrets: inherit
